use std::env;
use std::fs;
use std::fs::File;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;

fn main() {
    // Put `memory.x` in our output directory and ensure it's
    // on the linker search path.
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    File::create(out.join("memory.x"))
        .unwrap()
        .write_all(include_bytes!("memory.x"))
        .unwrap();
    println!("cargo:rustc-link-search={}", out.display());

    // By default, Cargo will re-run a build script whenever
    // any file in the project changes. By specifying `memory.x`
    // here, we ensure the build script is only re-run when
    // `memory.x` is changed.
    println!("cargo:rerun-if-changed=memory.x");

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-linker=flip-link");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tlink-rp.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");

    println!("cargo:rerun-if-changed=default.toml");
    println!("cargo:rerun-if-changed=local.toml");

    // Use config crate to load configuration
    let settings = config::Config::builder()
        .add_source(config::File::from(Path::new("default.toml")))
        .add_source(config::File::from(Path::new("local.toml")).required(false))
        .build()
        .expect("Failed to load configuration");

    // Extract WiFi settings
    let wifi_ssid = settings.get_string("wifi.ssid").expect("Missing wifi.ssid");
    let wifi_password = settings
        .get_string("wifi.password")
        .expect("Missing wifi.password");

    // Extract image download settings
    let image_url = settings
        .get_string("image.url")
        .expect("Missing image.url");
    let update_interval_minutes = settings
        .get::<u32>("image.update_interval_minutes")
        .expect("Missing image.update_interval_minutes");

    // Extract e-Paper settings
    let epaper_width = settings
        .get::<u16>("epaper.width")
        .expect("Missing epaper.width");
    let epaper_height = settings
        .get::<u16>("epaper.height")
        .expect("Missing epaper.height");
    let spi_frequency = settings
        .get::<u32>("epaper.spi_frequency")
        .expect("Missing epaper.spi_frequency");

    // Generate Rust code with constants
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("config_generated.rs");

    let generated_code = format!(
        r#"
// Auto-generated configuration file from default.toml and local.toml
// Do not edit this file manually!

// WiFi SSID
pub const WIFI_SSID: &str = "{}";

// WiFi password
pub const WIFI_PASSWORD: &str = "{}";

// Image URL (full HTTP URL)
pub const IMAGE_URL: &str = "{}";

// Image update interval in minutes
pub const UPDATE_INTERVAL_MINUTES: u32 = {};

// e-Paper display width
pub const EPAPER_WIDTH: u16 = {};

// e-Paper display height
pub const EPAPER_HEIGHT: u16 = {};

// SPI frequency for e-Paper
pub const SPI_FREQUENCY: u32 = {};
"#,
        wifi_ssid,
        wifi_password,
        image_url,
        update_interval_minutes,
        epaper_width,
        epaper_height,
        spi_frequency
    );

    fs::write(&dest_path, generated_code).expect("Failed to write generated config");

    println!("cargo:warning=Config generated from default.toml and local.toml");
}
